### ISSUE TITLE
和Coravel一起用的时候，直接运行能触发job，安装为服务后不能触发job

### ISSUE THREAD

**Issue by asine** [xljiulang/ServiceSelf#9]
.net 6.0 console app,把ServiceSelf1.0.7和Coravel5.0.4一起使用的时候，直接运行能触发Job，但是安装为服务后不能触发Job。[Coravel](https://www.nuget.org/packages/Coravel)

增加一个我建的测试程序，看看有什么不对的地方。
[ServiceSelfAndCoravelTest.zip](https://github.com/user-attachments/files/16477953/ServiceSelfAndCoravelTest.zip)

**Comment by xljiulang** [comment]
我运行你的demo，发现job正常多次触发

**Comment by xljiulang** [comment]
也许你的问题是：如何正确的使用Serilog，使其工作

**Comment by asine** [comment]
谢谢，明白了，直接运行和作为任务运行的当前目录是不一样。
